server:
  port: ${sp.resource}
spring:
  application:
    name: ${sn.resource}


knife4j:
  enableAggregation: false
  nacos:
    enable: true
    serviceUrl: http://${nacos.addr}/${nacos.contextPath}/
    # 注意：这里的路径配置需要配置到nacos配置中心system.yaml中
    routes:
      - name: 示例服务
        serviceName: ${sn.sample}
        namespaceId: ${nacos.namespace}
        location: /v2/api-docs?group=sample
      - name: 声明式CPP
        serviceName: ${sn.cpp}
        namespaceId: ${nacos.namespace}
        location: /v2/api-docs?group=cpp
      - name: 登录服务
        serviceName: ${sn.login}
        namespaceId: ${nacos.namespace}
        location: /v2/api-docs?group=login
