server:
  port: 10700
spring:
  application:
    name: MSG_NOTICE
#  datasource:
#    password: root
#    username: root
#    url: jdbc:mysql://localhost:3306
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 192.168.153.129                 # Redis 服务器地址
#    port: 6379                        # Redis 端口，默认是 6379
#    timeout: 3000                     # 连接超时时间，单位为毫秒
#    ssl: false                        # 是否启用 SSL 连接
#    database: 0                       # 使用的数据库索引，默认是 0

#关闭驼峰命名
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
