spring:
  datasource:
    url: jdbc:mysql://47.99.71.60:1578/test?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: c1znb666888
  redis:
    host: 182.92.161.6
    port: 9736
    password: redisPwanf502
  data:
   mongodb:
     uri: mongodb://c2:c2-123456qaq@8.148.21.89:27020/oac2