server:
  port: 10700

spring:
  application:
    name: SYS_BASIC

#  datasource:
#    url: jdbc:mysql://localhost:3306
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver